[build]
  command = "npm run build"
  publish = "dist/portafolio/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/node_modules/@lottiefiles/lottie-player/dist/tgs-player.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/node_modules/@lottiefiles/lottie-player/dist/tgs-player.js"
  to = "/assets/tgs-player.js"
  status = 200